<?php
wp_set_current_user( 1 );
$c = \Agentyllo\Plugin::instance()->container();
$cp = $c->get( \Agentyllo\Copilot\Copilot::class );
$r = $cp->handle( '/kb add title:"Return policy" content:"You can return any item within 30 days for a full refund. Contact support@example.test to start a return."' );
$prop = $r['blocks'][0];
echo "proposal: type={$prop['type']} action={$prop['action']} destructive=" . var_export( $prop['destructive'], true ) . " summary={$prop['summary']}\n";
$res = $cp->confirm( $prop['action'], $prop['args'], $prop['token'] );
echo "confirm: ok=" . var_export( $res['ok'], true ) . " msg={$res['message']}\n";
$again = $cp->confirm( $prop['action'], $prop['args'], $prop['token'] );
echo "replay token: ok=" . var_export( $again['ok'], true ) . " ({$again['message']})\n";
$doc = (int) $res['data']['document_id'];
$hits = $c->get( \Agentyllo\KB\Retrieval\HybridRetriever::class )->search( 'can I return an item?', array( 'limit' => 2 ) );
echo "retrieval: " . ( $hits ? $hits[0]['title'] . ' cov=' . $hits[0]['coverage'] : 'none' ) . "\n";
echo "free-text Q: " . wp_json_encode( $cp->handle( 'how do returns work?' )['blocks'][0]['md'] ) . "\n";
$list = $cp->handle( '/kb list' )['blocks'][0];
echo "list: {$list['message']}\n";
$stats = $cp->handle( '/stats query period:7d' )['blocks'][0];
echo "stats: {$stats['message']}\n";
$set = $cp->handle( '/settings set tab:general key:tone value:playful' )['blocks'][0];
echo "settings proposal: {$set['summary']} details=" . wp_json_encode( $set['details'] ) . "\n";
$setres = $cp->confirm( $set['action'], $set['args'], $set['token'] );
echo "settings applied: {$setres['message']}\n";
$cp->confirm( 'settings.set', array( 'tab' => 'general', 'key' => 'tone', 'value' => 'friendly' ), 'bogus|9999999999|x' );
$teach = $cp->handle( '/memory teach fact:"We are closed the whole month of August"' )['blocks'][0];
echo "teach: type={$teach['type']} — confirming…\n";
$tr = $cp->confirm( $teach['action'], $teach['args'], $teach['token'] );
echo "teach result: {$tr['message']} | memory.query: " . $cp->handle( '/memory query' )['blocks'][0]['message'] . "\n";
$del = $cp->handle( "/kb delete id:$doc" )['blocks'][0];
echo "delete proposal: destructive=" . var_export( $del['destructive'], true ) . " summary={$del['summary']}\n";
$dr = $cp->confirm( $del['action'], $del['args'], $del['token'] );
echo "delete: {$dr['message']} undo={$dr['data']['undo']}\n";
$hits2 = $c->get( \Agentyllo\KB\Retrieval\HybridRetriever::class )->search( 'return policy refund', array( 'limit' => 2 ) );
echo "after trash retrieval finds manual doc? " . ( array_filter( $hits2, fn( $h ) => (int) $h['document_id'] === $doc ) ? 'YES (bug)' : 'no (ok)' ) . "\n";
$restore = $cp->handle( "/kb restore id:$doc" )['blocks'][0];
$rr = $cp->confirm( $restore['action'], $restore['args'], $restore['token'] );
echo "restore: {$rr['message']}\n";
echo "help: " . substr( $cp->handle( '/help' )['blocks'][0]['md'], 0, 160 ) . "…\n";
// Reset tone.
$c->get( \Agentyllo\Admin\Settings\SettingsStore::class )->update( 'general', array( 'tone' => 'friendly' ) );
global $wpdb; echo "audit rows: " . $wpdb->get_var( "SELECT COUNT(*) FROM {$wpdb->prefix}agy_audit_log WHERE action LIKE 'copilot.%'" ) . "\n";
